# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Both',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_x', models.TextField()),
                ('both', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Both')),
                ('both_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Both')),
            ],
        ),
        migrations.CreateModel(
            name='InnerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_x', models.TextField()),
                ('both', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Both')),
                ('both_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Both')),
                ('inner_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.InnerClass')),
                ('inner_class_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.InnerClass')),
            ],
        ),
        migrations.CreateModel(
            name='Neither',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('both', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Both')),
                ('inner_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.InnerClass')),
                ('neither', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Neither')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('both', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Both')),
                ('inner_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.InnerClass')),
                ('neither', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Neither')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Settings')),
            ],
        ),
        migrations.AddField(
            model_name='neither',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Settings'),
        ),
        migrations.AddField(
            model_name='innerclass',
            name='neither',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Neither'),
        ),
        migrations.AddField(
            model_name='innerclass',
            name='neither_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Neither'),
        ),
        migrations.AddField(
            model_name='innerclass',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Settings'),
        ),
        migrations.AddField(
            model_name='innerclass',
            name='settings_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Settings'),
        ),
        migrations.AddField(
            model_name='both',
            name='inner_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.InnerClass'),
        ),
        migrations.AddField(
            model_name='both',
            name='inner_class_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.InnerClass'),
        ),
        migrations.AddField(
            model_name='both',
            name='neither',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Neither'),
        ),
        migrations.AddField(
            model_name='both',
            name='neither_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Neither'),
        ),
        migrations.AddField(
            model_name='both',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Settings'),
        ),
        migrations.AddField(
            model_name='both',
            name='settings_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='doink.Settings'),
        ),
    ]
